version: "3"
services:
  dev-nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev:/etc/nginx/templates
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    env_file:
      - .env
    ports:
      - 3000:80
    links:
      - dev-frontend
      - dev-backend

  dev-postgres:
    image: postgres:alpine
    container_name: tracker_postgres
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    restart: always

  dev-backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile-dev
    volumes: 
      - ./backend:/src
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    command: uvicorn --factory app:get_app --port 8000 --host 0.0.0.0 --reload
    restart: always
    links:
      - dev-postgres

  dev-frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile-dev
    volumes: 
      - ./frontend:/src
    command: npm start

volumes:
  pgdata-dev:
